import type {
  DashboardStats,
  RevenueData,
  UserGrowthData,
  User,
  Webtoon,
  Episode,
  Author,
  Genre,
  Comment,
  PopularWebtoon,
  MediaFile,
  ActivityLog,
  Report,
  Transaction,
  ScheduledEpisode,
  StoryChapter,
  SharedData,
} from './types'

export const mockDashboardStats: DashboardStats = {
  totalUsers: 125430,
  totalWebtoons: 892,
  totalEpisodes: 15678,
  totalViews: 4567890,
  totalRevenue: 125680,
  newUsersToday: 234,
  activeUsersToday: 8934,
  newEpisodesToday: 12,
}

export const mockRevenueData: RevenueData[] = [
  { date: '2026-04-01', revenue: 4200, coins: 42000 },
  { date: '2026-04-02', revenue: 3800, coins: 38000 },
  { date: '2026-04-03', revenue: 5100, coins: 51000 },
  { date: '2026-04-04', revenue: 4600, coins: 46000 },
  { date: '2026-04-05', revenue: 3900, coins: 39000 },
  { date: '2026-04-06', revenue: 5400, coins: 54000 },
  { date: '2026-04-07', revenue: 6200, coins: 62000 },
  { date: '2026-04-08', revenue: 5800, coins: 58000 },
  { date: '2026-04-09', revenue: 4900, coins: 49000 },
  { date: '2026-04-10', revenue: 5500, coins: 55000 },
  { date: '2026-04-11', revenue: 6100, coins: 61000 },
  { date: '2026-04-12', revenue: 7200, coins: 72000 },
  { date: '2026-04-13', revenue: 6800, coins: 68000 },
  { date: '2026-04-14', revenue: 5900, coins: 59000 },
]

export const mockUserGrowthData: UserGrowthData[] = [
  { date: '2026-03-27', users: 120000, activeUsers: 7500 },
  { date: '2026-04-03', users: 121500, activeUsers: 8100 },
  { date: '2026-04-10', users: 123200, activeUsers: 8400 },
  { date: '2026-04-17', users: 124500, activeUsers: 8700 },
  { date: '2026-04-24', users: 125430, activeUsers: 8934 },
]

export const mockPopularWebtoons: PopularWebtoon[] = [
  {
    id: '1',
    title: { mm: 'The Last Horizon', en: 'The Last Horizon' },
    views: 2500000,
    likes: 125000,
    revenue: 12500,
  },
  {
    id: '3',
    title: { mm: 'Shadow Knight', en: 'Shadow Knight' },
    views: 3200000,
    likes: 156000,
    revenue: 15600,
  },
  {
    id: '2',
    title: { mm: 'ဆိုးလ်မြို့က ချစ်ခြင်းတရား', en: 'Love in Seoul' },
    views: 1800000,
    likes: 98000,
    revenue: 9800,
  },
  {
    id: '7',
    title: { mm: 'သွေးနက်လ', en: 'Blood Moon' },
    views: 1100000,
    likes: 78000,
    revenue: 7800,
  },
  {
    id: '8',
    title: { mm: 'Cyber Dreams', en: 'Cyber Dreams' },
    views: 980000,
    likes: 72000,
    revenue: 7200,
  },
]

export const mockAuthors: Author[] = [
  {
    id: '1',
    name: { mm: 'ကိုဇော်', en: 'Ko Zaw' },
    bio: { mm: 'Webtoon ပန်းချီဆရာနှင့် ဇာတ်လမ်းရေးဆရာ', en: 'Webtoon artist and storyteller' },
    followerCount: 125000,
    webtoonCount: 5,
    status: 'active',
  },
  {
    id: '2',
    name: { mm: 'မသူဇာ', en: 'Ma Thuzar' },
    bio: { mm: 'အချစ်ဇာတ်လမ်း Webtoon ဖန်တီးသူ', en: 'Romance webtoon creator' },
    followerCount: 89000,
    webtoonCount: 3,
    status: 'active',
  },
  {
    id: '3',
    name: { mm: 'ကိုထက်', en: 'Ko Htet' },
    bio: { mm: 'အက်ရှင်နှင့် စိတ်ကူးယဉ်ကားများ ဝါသနာပါသူ', en: 'Action and fantasy enthusiast' },
    followerCount: 156000,
    webtoonCount: 7,
    status: 'active',
  },
  {
    id: '4',
    name: { mm: 'မအေး', en: 'Ma Aye' },
    bio: { mm: 'အနုပညာဖြင့် ကမ္ဘာများကို ဖန်တီးသူ', en: 'Creating worlds through art' },
    followerCount: 78000,
    webtoonCount: 4,
    status: 'active',
  },
  {
    id: '5',
    name: { mm: 'ကိုမြင့်', en: 'Ko Myint' },
    bio: {
      mm: 'ကြောက်ရွံ့ဖွယ်နှင့် စိတ်လှုပ်ရှားဖွယ် ကားများ အထူးပြု',
      en: 'Horror and thriller specialist',
    },
    followerCount: 92000,
    webtoonCount: 6,
    status: 'inactive',
  },
]

export const mockGenres: Genre[] = [
  {
    id: '1',
    name: { mm: 'အားလုံး', en: 'All' },
    slug: 'all',
    description: 'All genres',
    webtoonCount: 892,
  },
  {
    id: '2',
    name: { mm: 'အက်ရှင်', en: 'Action' },
    slug: 'action',
    description: 'Action-packed stories',
    webtoonCount: 156,
  },
  {
    id: '3',
    name: { mm: 'အချစ်ဇာတ်လမ်း', en: 'Romance' },
    slug: 'romance',
    description: 'Love stories',
    webtoonCount: 234,
  },
  {
    id: '4',
    name: { mm: 'စိတ်ကူးယဉ်', en: 'Fantasy' },
    slug: 'fantasy',
    description: 'Magical worlds',
    webtoonCount: 189,
  },
  {
    id: '5',
    name: { mm: 'ဟာသ', en: 'Comedy' },
    slug: 'comedy',
    description: 'Funny stories',
    webtoonCount: 98,
  },
  {
    id: '6',
    name: { mm: 'ဒရမ်မာ', en: 'Drama' },
    slug: 'drama',
    description: 'Emotional stories',
    webtoonCount: 145,
  },
  {
    id: '7',
    name: { mm: 'ကြောက်ရွံ့ဖွယ်', en: 'Horror' },
    slug: 'horror',
    description: 'Scary stories',
    webtoonCount: 67,
  },
  {
    id: '8',
    name: { mm: 'သိပ္ပံစိတ်ကူးယဉ်', en: 'Sci-Fi' },
    slug: 'sci-fi',
    description: 'Science fiction',
    webtoonCount: 45,
  },
  {
    id: '9',
    name: { mm: 'စိတ်လှုပ်ရှားဖွယ်', en: 'Thriller' },
    slug: 'thriller',
    description: 'Suspenseful stories',
    webtoonCount: 78,
  },
  {
    id: '10',
    name: { mm: 'နေ့စဉ်ဘဝ', en: 'Slice of Life' },
    slug: 'slice-of-life',
    description: 'Daily life stories',
    webtoonCount: 56,
  },
  {
    id: '11',
    name: { mm: 'သမိုင်း', en: 'Historical' },
    slug: 'historical',
    description: 'Stories set in the past',
    webtoonCount: 40,
  },
  {
    id: '12',
    name: { mm: 'လျှို့ဝှက်ဆန်းကြယ်', en: 'Mystery' },
    slug: 'mystery',
    description: 'Mystery and investigation',
    webtoonCount: 52,
  },
  {
    id: '13',
    name: { mm: 'သဘာဝလွန်', en: 'Supernatural' },
    slug: 'supernatural',
    description: 'Ghosts, spirits, and the unexplained',
    webtoonCount: 61,
  },
  {
    id: '14',
    name: { mm: 'စွန့်စားမှု', en: 'Adventure' },
    slug: 'adventure',
    description: 'Journeys and exploration',
    webtoonCount: 70,
  },
  {
    id: '15',
    name: { mm: 'အားကစား', en: 'Sports' },
    slug: 'sports',
    description: 'Athletic competition stories',
    webtoonCount: 34,
  },
  {
    id: '16',
    name: { mm: 'သူရဲကောင်း', en: 'Superhero' },
    slug: 'superhero',
    description: 'Heroes with extraordinary powers',
    webtoonCount: 48,
  },
]

export const mockWebtoons: Webtoon[] = [
  {
    id: '1',
    title: { mm: 'The Last Horizon', en: 'The Last Horizon' },
    description: {
      mm: 'မှော်နှင့် နည်းပညာတို့ တိုက်ခိုက်ရသော ကမ္ဘာတစ်ခုတွင် သူရဲကောင်းတစ်ဦးသည် လူသားမျိုးနွယ်ကို ပျက်စီးခြင်းမှ ကယ်တင်ရန် ထွန်းလင်းတောက်ပရမည်။',
      en: 'In a world where magic and technology clash, a hero must rise to save humanity from destruction.',
    },
    coverImage: '/webtoon-covers/the-last-horizon.png',
    coverColor: 'bg-gradient-to-br from-primary-400 to-primary-600',
    author: mockAuthors[0],
    genres: ['အက်ရှင်', 'စိတ်ကူးယဉ်'],
    tags: ['မှော်', 'နည်းပညာ', 'စွန့်စားမှု'],
    status: 'ongoing',
    isPremium: false,
    viewCount: 2500000,
    likeCount: 125000,
    episodeCount: 5,
    rating: 4.9,
    contentRating: '13',
    createdAt: '2026-01-22',
    updatedAt: '2026-08-18',
    weeklyViewCount: 12000,
  },
  {
    id: '2',
    title: { mm: 'ဆိုးလ်မြို့က ချစ်ခြင်းတရား', en: 'Love in Seoul' },
    description: {
      mm: 'ဆိုးလ်မြို့၏ လူစည်ကားသော လမ်းမကြီးများတွင် ဖြစ်ပွားသော နွေးထွေးလှသည့် အချစ်ဇာတ်လမ်းတစ်ပုဒ်။',
      en: 'A heartwarming love story set in the bustling streets of Seoul.',
    },
    coverImage: '/webtoon-covers/love-in-seoul.png',
    coverColor: 'bg-gradient-to-br from-pink-400 to-rose-600',
    author: mockAuthors[1],
    genres: ['အချစ်ဇာတ်လမ်း', 'ဟာသ'],
    tags: ['အချစ်', 'ဆိုးလ်', 'နေ့စဉ်ဘဝ'],
    status: 'ongoing',
    isPremium: false,
    viewCount: 1800000,
    likeCount: 98000,
    episodeCount: 3,
    rating: 4.7,
    contentRating: '13',
    createdAt: '2026-03-12',
    updatedAt: '2026-03-28',
    spotlight: true,
    spotlightOrder: 1,
    weeklyViewCount: 35000,
  },
  {
    id: '3',
    title: { mm: 'Shadow Knight', en: 'Shadow Knight' },
    description: {
      mm: 'နိုင်ငံတော်ကို ကာကွယ်ရန် အမှောင်ထဲမှ ထွက်ပေါ်လာသော ထူးချွန်သည့် စစ်သည်တော်တစ်ဦး။',
      en: 'An elite soldier emerges from the shadows to protect the nation.',
    },
    coverImage: '/webtoon-covers/shadow-knight.png',
    coverColor: 'bg-gradient-to-br from-slate-600 to-gray-900',
    author: mockAuthors[2],
    genres: ['အက်ရှင်', 'သူရဲကောင်း'],
    tags: ['စစ်သည်', 'နိုင်ငံတော်', 'စွန့်စားမှု'],
    status: 'ongoing',
    isPremium: true,
    viewCount: 3200000,
    likeCount: 156000,
    episodeCount: 3,
    rating: 4.8,
    contentRating: '16',
    createdAt: '2026-01-08',
    updatedAt: '2026-08-19',
    spotlight: true,
    spotlightOrder: 4,
    weeklyViewCount: 15000,
  },
  {
    id: '4',
    title: { mm: 'Ocean Dreams', en: 'Ocean Dreams' },
    description: {
      mm: 'ပင်လယ်ခုနစ်စင်းကို ဖြတ်ကျော်သော စွန့်စားမှုဇာတ်လမ်း။',
      en: 'An adventure across the seven seas.',
    },
    coverImage: '/webtoon-covers/ocean-dreams.png',
    coverColor: 'bg-gradient-to-br from-cyan-400 to-blue-600',
    author: mockAuthors[3],
    genres: ['စွန့်စားမှု', 'စိတ်ကူးယဉ်'],
    tags: ['ပင်လယ်', 'စွန့်စားမှု', 'ပင်လယ်ဓားပြ'],
    status: 'ongoing',
    isPremium: false,
    viewCount: 890000,
    likeCount: 67000,
    episodeCount: 3,
    rating: 4.6,
    contentRating: 'all',
    createdAt: '2026-06-14',
    updatedAt: '2026-06-28',
    spotlight: true,
    spotlightOrder: 2,
    weeklyViewCount: 80000,
  },
  {
    id: '5',
    title: { mm: 'ရွှေခေတ်', en: 'Golden Age' },
    description: {
      mm: 'ရှေးခေတ်တွင် ဖြစ်ပွားသော သမိုင်းဝင် ဇာတ်လမ်းကြီးတစ်ပုဒ်။',
      en: 'An epic historical saga set in ancient times.',
    },
    coverImage: '/webtoon-covers/golden-age.png',
    coverColor: 'bg-gradient-to-br from-amber-400 to-orange-600',
    author: mockAuthors[4],
    genres: ['သမိုင်း', 'ဒရမ်မာ'],
    tags: ['သမိုင်း', 'ရှေးခေတ်', 'ဇာတ်လမ်းကြီး'],
    status: 'completed',
    isPremium: false,
    viewCount: 1500000,
    likeCount: 89000,
    episodeCount: 3,
    rating: 4.8,
    contentRating: '13',
    createdAt: '2026-02-04',
    updatedAt: '2026-08-16',
    weeklyViewCount: 5000,
  },
  {
    id: '6',
    title: { mm: 'Forest Spirit', en: 'Forest Spirit' },
    description: {
      mm: 'စုန်းအင်းတောများကို ဖြတ်ကျော်သော မှော်ဆန်သည့် ခရီးစဉ်။',
      en: 'A magical journey through enchanted forests.',
    },
    coverImage: '/webtoon-covers/forest-spirit.png',
    coverColor: 'bg-gradient-to-br from-emerald-400 to-teal-600',
    author: mockAuthors[0],
    genres: ['စိတ်ကူးယဉ်', 'သဘာဝလွန်'],
    tags: ['မှော်', 'တော', 'နတ်များ'],
    status: 'hiatus',
    isPremium: false,
    viewCount: 720000,
    likeCount: 54000,
    episodeCount: 3,
    rating: 4.5,
    contentRating: 'all',
    createdAt: '2026-07-08',
    updatedAt: '2026-07-20',
    weeklyViewCount: 95000,
  },
  {
    id: '7',
    title: { mm: 'သွေးနက်လ', en: 'Blood Moon' },
    description: {
      mm: 'သင့်ကို ခုံရင်ခွဲစေမည့် ကြောက်ရွံ့ဖွယ် ဇာတ်လမ်း။',
      en: 'A terrifying horror story that will keep you on the edge.',
    },
    coverImage: '/webtoon-covers/blood-moon.png',
    coverColor: 'bg-gradient-to-br from-red-500 to-rose-700',
    author: mockAuthors[4],
    genres: ['ကြောက်ရွံ့ဖွယ်', 'စိတ်လှုပ်ရှားဖွယ်'],
    tags: ['ကြောက်ရွံ့ဖွယ်', 'ထူးဆန်း', 'လျှို့ဝှက်ချက်'],
    status: 'ongoing',
    isPremium: true,
    viewCount: 1100000,
    likeCount: 78000,
    episodeCount: 3,
    rating: 4.7,
    contentRating: '18',
    createdAt: '2026-04-03',
    updatedAt: '2026-04-20',
    weeklyViewCount: 20000,
  },
  {
    id: '8',
    title: { mm: 'Cyber Dreams', en: 'Cyber Dreams' },
    description: {
      mm: 'ဆိုက်ဘာပန့်ကမ္ဘာတွင် သိပ္ပံစိတ်ကူးယဉ် စွန့်စားမှု။',
      en: 'A sci-fi adventure in a cyberpunk world.',
    },
    coverImage: '/webtoon-covers/cyber-dreams.png',
    coverColor: 'bg-gradient-to-br from-violet-500 to-purple-700',
    author: mockAuthors[2],
    genres: ['သိပ္ပံစိတ်ကူးယဉ်', 'လျှို့ဝှက်ဆန်းကြယ်'],
    tags: ['ဆိုက်ဘာပန့်', 'အနာဂတ်', 'နည်းပညာ'],
    status: 'ongoing',
    isPremium: false,
    viewCount: 980000,
    likeCount: 72000,
    episodeCount: 3,
    rating: 4.6,
    contentRating: '16',
    createdAt: '2026-05-09',
    updatedAt: '2026-05-26',
    spotlight: true,
    spotlightOrder: 5,
    weeklyViewCount: 40000,
  },
  {
    id: '9',
    title: { mm: 'တက္ကသိုလ်ဘဝ', en: 'Campus Life' },
    description: {
      mm: 'တက္ကသိုလ်ကျောင်းသားများ၏ နေ့စဉ်ဘဝ ဇာတ်လမ်း။',
      en: 'Daily life stories of university students.',
    },
    coverImage: '/webtoon-covers/campus-life.png',
    coverColor: 'bg-gradient-to-br from-sky-400 to-indigo-500',
    author: mockAuthors[1],
    genres: ['နေ့စဉ်ဘဝ', 'အားကစား'],
    tags: ['တက္ကသိုလ်', 'ဟာသ', 'အားကစား'],
    status: 'ongoing',
    isPremium: false,
    viewCount: 650000,
    likeCount: 48000,
    episodeCount: 3,
    rating: 4.4,
    contentRating: '13',
    createdAt: '2026-08-10',
    updatedAt: '2026-08-12',
    spotlight: true,
    spotlightOrder: 3,
    weeklyViewCount: 120000,
  },
]

function syncMockGenreCounts() {
  const norm = (value: string) => value.trim().toLowerCase()
  const published = mockWebtoons.filter((w) => w.status !== 'draft')
  for (const genre of mockGenres) {
    if (genre.slug === 'all') {
      genre.webtoonCount = published.length
      continue
    }
    const aliases = new Set([genre.name.mm, genre.name.en, genre.slug].map(norm).filter(Boolean))
    genre.webtoonCount = published.filter((w) =>
      w.genres.some((label) => aliases.has(norm(label)))
    ).length
  }
}

syncMockGenreCounts()

function scheduledDrop(partial: {
  id: string
  webtoonId: string
  episodeNumber: number
  title: Episode['title']
  scheduledAt: string
}): Episode {
  const series = mockWebtoons.find((webtoon) => webtoon.id === partial.webtoonId)
  if (!series) {
    throw new Error(`scheduledDrop: missing series ${partial.webtoonId}`)
  }
  return {
    id: partial.id,
    webtoonId: partial.webtoonId,
    webtoonTitle: series.title,
    title: partial.title,
    description: { mm: 'ချိန်းထားသော အပိုင်း', en: 'Scheduled episode' },
    images: [],
    isPremium: series.isPremium,
    coinPrice: series.isPremium ? 5 : 0,
    viewCount: 0,
    likeCount: 0,
    episodeNumber: partial.episodeNumber,
    status: 'scheduled',
    createdAt: series.updatedAt,
    updatedAt: series.updatedAt,
    scheduledAt: partial.scheduledAt,
  }
}

export const mockEpisodes: Episode[] = [
  {
    id: '1',
    webtoonId: '1',
    webtoonTitle: { mm: 'The Last Horizon', en: 'The Last Horizon' },
    title: { mm: 'အစပြုခြင်း', en: 'The Beginning' },
    description: { mm: 'ခရီးစဉ် ဤနေရာမှ စတင်သည်...', en: 'The journey starts here...' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 125000,
    likeCount: 8500,
    episodeNumber: 1,
    status: 'published',
    createdAt: '2026-01-22',
    updatedAt: '2026-01-22',
  },
  {
    id: '2',
    webtoonId: '1',
    webtoonTitle: { mm: 'The Last Horizon', en: 'The Last Horizon' },
    title: { mm: 'နိုးထခြင်း', en: 'Awakening' },
    description: { mm: 'စွမ်းအားများ စတင်ထွက်ပေါ်လာသည်...', en: 'Powers begin to emerge...' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 102000,
    likeCount: 7200,
    episodeNumber: 2,
    status: 'published',
    createdAt: '2026-03-06',
    updatedAt: '2026-03-06',
  },
  {
    id: '3',
    webtoonId: '1',
    webtoonTitle: { mm: 'The Last Horizon', en: 'The Last Horizon' },
    title: { mm: 'ပထမဆုံးတိုက်ပွဲ', en: 'First Battle' },
    description: { mm: 'ပထမဆုံး စိန်ခေါ်မှု ပေါ်လာသည်...', en: 'The first challenge appears...' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 87000,
    likeCount: 6100,
    episodeNumber: 3,
    status: 'published',
    createdAt: '2026-04-20',
    updatedAt: '2026-04-20',
  },
  {
    id: '4',
    webtoonId: '1',
    webtoonTitle: { mm: 'The Last Horizon', en: 'The Last Horizon' },
    title: { mm: 'လေ့ကျင့်ခန်း', en: 'Training' },
    description: {
      mm: 'စွမ်းအားကို ထိန်းချုပ်တတ်အောင် သင်ယူခြင်း...',
      en: 'Learning to control the power...',
    },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: true,
    coinPrice: 5,
    viewCount: 71000,
    likeCount: 5300,
    episodeNumber: 4,
    status: 'published',
    createdAt: '2026-06-04',
    updatedAt: '2026-06-04',
  },
  {
    id: '5',
    webtoonId: '1',
    webtoonTitle: { mm: 'The Last Horizon', en: 'The Last Horizon' },
    title: { mm: 'အမှောင်လျှို့ဝှက်ချက်များ', en: 'Dark Secrets' },
    description: {
      mm: 'ဖုံးကွယ်ထားသော အမှန်တရားများ ထွက်ပေါ်လာသည်...',
      en: 'Hidden truths begin to surface...',
    },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: true,
    coinPrice: 5,
    viewCount: 65000,
    likeCount: 4800,
    episodeNumber: 5,
    status: 'published',
    createdAt: '2026-08-18',
    updatedAt: '2026-08-18',
    freeAt: '2026-08-26T05:00:00.000Z',
  },
  {
    id: '6',
    webtoonId: '2',
    webtoonTitle: { mm: 'ဆိုးလ်မြို့က ချစ်ခြင်းတရား', en: 'Love in Seoul' },
    title: { mm: 'အပိုင်း 1', en: 'Episode 1' },
    description: { mm: 'အပိုင်း 1 အကျဉ်းချုပ်', en: 'Episode 1 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 43000,
    likeCount: 3550,
    episodeNumber: 1,
    status: 'published',
    createdAt: '2026-03-12',
    updatedAt: '2026-03-12',
  },
  {
    id: '7',
    webtoonId: '2',
    webtoonTitle: { mm: 'ဆိုးလ်မြို့က ချစ်ခြင်းတရား', en: 'Love in Seoul' },
    title: { mm: 'အပိုင်း 2', en: 'Episode 2' },
    description: { mm: 'အပိုင်း 2 အကျဉ်းချုပ်', en: 'Episode 2 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 42000,
    likeCount: 3500,
    episodeNumber: 2,
    status: 'published',
    createdAt: '2026-03-20',
    updatedAt: '2026-03-20',
  },
  {
    id: '8',
    webtoonId: '2',
    webtoonTitle: { mm: 'ဆိုးလ်မြို့က ချစ်ခြင်းတရား', en: 'Love in Seoul' },
    title: { mm: 'အပိုင်း 3', en: 'Episode 3' },
    description: { mm: 'အပိုင်း 3 အကျဉ်းချုပ်', en: 'Episode 3 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: true,
    coinPrice: 5,
    viewCount: 41000,
    likeCount: 3450,
    episodeNumber: 3,
    status: 'published',
    createdAt: '2026-03-28',
    updatedAt: '2026-03-28',
    freeAt: '2026-08-07T05:00:00.000Z',
  },
  {
    id: '9',
    webtoonId: '3',
    webtoonTitle: { mm: 'Shadow Knight', en: 'Shadow Knight' },
    title: { mm: 'အပိုင်း 1', en: 'Episode 1' },
    description: { mm: 'အပိုင်း 1 အကျဉ်းချုပ်', en: 'Episode 1 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 40000,
    likeCount: 3350,
    episodeNumber: 1,
    status: 'published',
    createdAt: '2026-01-08',
    updatedAt: '2026-01-08',
  },
  {
    id: '10',
    webtoonId: '3',
    webtoonTitle: { mm: 'Shadow Knight', en: 'Shadow Knight' },
    title: { mm: 'အပိုင်း 2', en: 'Episode 2' },
    description: { mm: 'အပိုင်း 2 အကျဉ်းချုပ်', en: 'Episode 2 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 39000,
    likeCount: 3300,
    episodeNumber: 2,
    status: 'published',
    createdAt: '2026-04-16',
    updatedAt: '2026-04-16',
  },
  {
    id: '11',
    webtoonId: '3',
    webtoonTitle: { mm: 'Shadow Knight', en: 'Shadow Knight' },
    title: { mm: 'အပိုင်း 3', en: 'Episode 3' },
    description: { mm: 'အပိုင်း 3 အကျဉ်းချုပ်', en: 'Episode 3 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: true,
    coinPrice: 5,
    viewCount: 38000,
    likeCount: 3250,
    episodeNumber: 3,
    status: 'published',
    createdAt: '2026-08-19',
    updatedAt: '2026-08-19',
    freeAt: '2026-08-26T05:00:00.000Z',
  },
  {
    id: '12',
    webtoonId: '4',
    webtoonTitle: { mm: 'Ocean Dreams', en: 'Ocean Dreams' },
    title: { mm: 'အပိုင်း 1', en: 'Episode 1' },
    description: { mm: 'အပိုင်း 1 အကျဉ်းချုပ်', en: 'Episode 1 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 37000,
    likeCount: 3150,
    episodeNumber: 1,
    status: 'published',
    createdAt: '2026-06-14',
    updatedAt: '2026-06-14',
  },
  {
    id: '13',
    webtoonId: '4',
    webtoonTitle: { mm: 'Ocean Dreams', en: 'Ocean Dreams' },
    title: { mm: 'အပိုင်း 2', en: 'Episode 2' },
    description: { mm: 'အပိုင်း 2 အကျဉ်းချုပ်', en: 'Episode 2 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 36000,
    likeCount: 3100,
    episodeNumber: 2,
    status: 'published',
    createdAt: '2026-06-21',
    updatedAt: '2026-06-21',
  },
  {
    id: '14',
    webtoonId: '4',
    webtoonTitle: { mm: 'Ocean Dreams', en: 'Ocean Dreams' },
    title: { mm: 'အပိုင်း 3', en: 'Episode 3' },
    description: { mm: 'အပိုင်း 3 အကျဉ်းချုပ်', en: 'Episode 3 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: true,
    coinPrice: 5,
    viewCount: 35000,
    likeCount: 3050,
    episodeNumber: 3,
    status: 'published',
    createdAt: '2026-06-28',
    updatedAt: '2026-06-28',
    freeAt: '2026-08-10T05:00:00.000Z',
  },
  {
    id: '15',
    webtoonId: '5',
    webtoonTitle: { mm: 'ရွှေခေတ်', en: 'Golden Age' },
    title: { mm: 'အပိုင်း 1', en: 'Episode 1' },
    description: { mm: 'အပိုင်း 1 အကျဉ်းချုပ်', en: 'Episode 1 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 34000,
    likeCount: 2950,
    episodeNumber: 1,
    status: 'published',
    createdAt: '2026-02-04',
    updatedAt: '2026-02-04',
  },
  {
    id: '16',
    webtoonId: '5',
    webtoonTitle: { mm: 'ရွှေခေတ်', en: 'Golden Age' },
    title: { mm: 'အပိုင်း 2', en: 'Episode 2' },
    description: { mm: 'အပိုင်း 2 အကျဉ်းချုပ်', en: 'Episode 2 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 33000,
    likeCount: 2900,
    episodeNumber: 2,
    status: 'published',
    createdAt: '2026-04-13',
    updatedAt: '2026-04-13',
  },
  {
    id: '17',
    webtoonId: '5',
    webtoonTitle: { mm: 'ရွှေခေတ်', en: 'Golden Age' },
    title: { mm: 'အပိုင်း 3', en: 'Episode 3' },
    description: { mm: 'အပိုင်း 3 အကျဉ်းချုပ်', en: 'Episode 3 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: true,
    coinPrice: 5,
    viewCount: 32000,
    likeCount: 2850,
    episodeNumber: 3,
    status: 'published',
    createdAt: '2026-08-16',
    updatedAt: '2026-08-16',
  },
  {
    id: '18',
    webtoonId: '6',
    webtoonTitle: { mm: 'Forest Spirit', en: 'Forest Spirit' },
    title: { mm: 'အပိုင်း 1', en: 'Episode 1' },
    description: { mm: 'အပိုင်း 1 အကျဉ်းချုပ်', en: 'Episode 1 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 31000,
    likeCount: 2750,
    episodeNumber: 1,
    status: 'published',
    createdAt: '2026-07-08',
    updatedAt: '2026-07-08',
  },
  {
    id: '19',
    webtoonId: '6',
    webtoonTitle: { mm: 'Forest Spirit', en: 'Forest Spirit' },
    title: { mm: 'အပိုင်း 2', en: 'Episode 2' },
    description: { mm: 'အပိုင်း 2 အကျဉ်းချုပ်', en: 'Episode 2 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 30000,
    likeCount: 2700,
    episodeNumber: 2,
    status: 'published',
    createdAt: '2026-07-14',
    updatedAt: '2026-07-14',
  },
  {
    id: '20',
    webtoonId: '6',
    webtoonTitle: { mm: 'Forest Spirit', en: 'Forest Spirit' },
    title: { mm: 'အပိုင်း 3', en: 'Episode 3' },
    description: { mm: 'အပိုင်း 3 အကျဉ်းချုပ်', en: 'Episode 3 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: true,
    coinPrice: 5,
    viewCount: 29000,
    likeCount: 2650,
    episodeNumber: 3,
    status: 'published',
    createdAt: '2026-07-20',
    updatedAt: '2026-07-20',
  },
  {
    id: '21',
    webtoonId: '7',
    webtoonTitle: { mm: 'သွေးနက်လ', en: 'Blood Moon' },
    title: { mm: 'အပိုင်း 1', en: 'Episode 1' },
    description: { mm: 'အပိုင်း 1 အကျဉ်းချုပ်', en: 'Episode 1 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 28000,
    likeCount: 2550,
    episodeNumber: 1,
    status: 'published',
    createdAt: '2026-04-03',
    updatedAt: '2026-04-03',
  },
  {
    id: '22',
    webtoonId: '7',
    webtoonTitle: { mm: 'သွေးနက်လ', en: 'Blood Moon' },
    title: { mm: 'အပိုင်း 2', en: 'Episode 2' },
    description: { mm: 'အပိုင်း 2 အကျဉ်းချုပ်', en: 'Episode 2 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 27000,
    likeCount: 2500,
    episodeNumber: 2,
    status: 'published',
    createdAt: '2026-04-12',
    updatedAt: '2026-04-12',
  },
  {
    id: '23',
    webtoonId: '7',
    webtoonTitle: { mm: 'သွေးနက်လ', en: 'Blood Moon' },
    title: { mm: 'အပိုင်း 3', en: 'Episode 3' },
    description: { mm: 'အပိုင်း 3 အကျဉ်းချုပ်', en: 'Episode 3 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: true,
    coinPrice: 5,
    viewCount: 26000,
    likeCount: 2450,
    episodeNumber: 3,
    status: 'published',
    createdAt: '2026-04-20',
    updatedAt: '2026-04-20',
    freeAt: '2026-08-24T12:00:00.000Z',
  },
  {
    id: '24',
    webtoonId: '8',
    webtoonTitle: { mm: 'Cyber Dreams', en: 'Cyber Dreams' },
    title: { mm: 'အပိုင်း 1', en: 'Episode 1' },
    description: { mm: 'အပိုင်း 1 အကျဉ်းချုပ်', en: 'Episode 1 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 25000,
    likeCount: 2350,
    episodeNumber: 1,
    status: 'published',
    createdAt: '2026-05-09',
    updatedAt: '2026-05-09',
  },
  {
    id: '25',
    webtoonId: '8',
    webtoonTitle: { mm: 'Cyber Dreams', en: 'Cyber Dreams' },
    title: { mm: 'အပိုင်း 2', en: 'Episode 2' },
    description: { mm: 'အပိုင်း 2 အကျဉ်းချုပ်', en: 'Episode 2 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 24000,
    likeCount: 2300,
    episodeNumber: 2,
    status: 'published',
    createdAt: '2026-05-18',
    updatedAt: '2026-05-18',
  },
  {
    id: '26',
    webtoonId: '8',
    webtoonTitle: { mm: 'Cyber Dreams', en: 'Cyber Dreams' },
    title: { mm: 'အပိုင်း 3', en: 'Episode 3' },
    description: { mm: 'အပိုင်း 3 အကျဉ်းချုပ်', en: 'Episode 3 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: true,
    coinPrice: 5,
    viewCount: 23000,
    likeCount: 2250,
    episodeNumber: 3,
    status: 'published',
    createdAt: '2026-05-26',
    updatedAt: '2026-05-26',
    freeAt: '2026-08-14T05:00:00.000Z',
  },
  {
    id: '27',
    webtoonId: '9',
    webtoonTitle: { mm: 'တက္ကသိုလ်ဘဝ', en: 'Campus Life' },
    title: { mm: 'အပိုင်း 1', en: 'Episode 1' },
    description: { mm: 'အပိုင်း 1 အကျဉ်းချုပ်', en: 'Episode 1 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 22000,
    likeCount: 2150,
    episodeNumber: 1,
    status: 'published',
    createdAt: '2026-08-10',
    updatedAt: '2026-08-10',
  },
  {
    id: '28',
    webtoonId: '9',
    webtoonTitle: { mm: 'တက္ကသိုလ်ဘဝ', en: 'Campus Life' },
    title: { mm: 'အပိုင်း 2', en: 'Episode 2' },
    description: { mm: 'အပိုင်း 2 အကျဉ်းချုပ်', en: 'Episode 2 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: false,
    coinPrice: 0,
    viewCount: 21000,
    likeCount: 2100,
    episodeNumber: 2,
    status: 'published',
    createdAt: '2026-08-12',
    updatedAt: '2026-08-12',
  },
  {
    id: '29',
    webtoonId: '9',
    webtoonTitle: { mm: 'တက္ကသိုလ်ဘဝ', en: 'Campus Life' },
    title: { mm: 'အပိုင်း 3', en: 'Episode 3' },
    description: { mm: 'အပိုင်း 3 အကျဉ်းချုပ်', en: 'Episode 3 summary' },
    images: [
      '/webtoon-covers/the-last-horizon.png',
      '/webtoon-covers/love-in-seoul.png',
      '/webtoon-covers/shadow-knight.png',
      '/webtoon-covers/ocean-dreams.png',
    ],
    isPremium: true,
    coinPrice: 5,
    viewCount: 20000,
    likeCount: 2050,
    episodeNumber: 3,
    status: 'published',
    createdAt: '2026-08-12',
    updatedAt: '2026-08-12',
    freeAt: '2026-08-22T05:00:00.000Z',
  },
  scheduledDrop({
    id: 'sched-1',
    webtoonId: '1',
    episodeNumber: 6,
    title: { mm: 'နောက်တံခါး', en: 'The Next Gate' },
    scheduledAt: '2026-08-24T05:00:00.000Z',
  }),
  scheduledDrop({
    id: 'sched-1b',
    webtoonId: '1',
    episodeNumber: 7,
    title: { mm: 'မုန်တိုင်းအပြီး', en: 'After the Storm' },
    scheduledAt: '2026-08-21T05:00:00.000Z',
  }),
  scheduledDrop({
    id: 'sched-2',
    webtoonId: '2',
    episodeNumber: 4,
    title: { mm: 'မိုးရွာသောည', en: 'Rainy Night' },
    scheduledAt: '2026-08-25T05:00:00.000Z',
  }),
  scheduledDrop({
    id: 'sched-3',
    webtoonId: '3',
    episodeNumber: 4,
    title: { mm: 'အရိပ်ထဲမှ ဓား', en: 'Blade in Shadow' },
    scheduledAt: '2026-08-19T05:00:00.000Z',
  }),
  scheduledDrop({
    id: 'sched-4',
    webtoonId: '4',
    episodeNumber: 4,
    title: { mm: 'ခုနစ်စင်းမြောက် လှိုင်း', en: 'Seventh Wave' },
    scheduledAt: '2026-08-23T05:00:00.000Z',
  }),
  scheduledDrop({
    id: 'sched-7',
    webtoonId: '7',
    episodeNumber: 4,
    title: { mm: 'နီသောလကြတ်', en: 'Crimson Eclipse' },
    scheduledAt: '2026-08-20T05:00:00.000Z',
  }),
  scheduledDrop({
    id: 'sched-8',
    webtoonId: '8',
    episodeNumber: 4,
    title: { mm: 'နက်ဗ်ဝါးခ် ကျိုးခြင်း', en: 'Network Break' },
    scheduledAt: '2026-08-21T08:00:00.000Z',
  }),
  scheduledDrop({
    id: 'sched-9',
    webtoonId: '9',
    episodeNumber: 4,
    title: { mm: 'ပထမဆုံး ပြိုင်ပွဲ', en: 'First Match' },
    scheduledAt: '2026-08-22T05:00:00.000Z',
  }),
  {
    id: 'draft-1-99',
    webtoonId: '1',
    webtoonTitle: { mm: 'The Last Horizon', en: 'The Last Horizon' },
    title: { mm: 'မူကြမ်း အပိုင်း', en: 'Draft episode' },
    description: { mm: 'ထုတ်ဝေမထားသော အပိုင်း', en: 'Unpublished episode' },
    images: ['/webtoon-covers/the-last-horizon.png'],
    isPremium: false,
    coinPrice: 0,
    viewCount: 0,
    likeCount: 0,
    episodeNumber: 99,
    status: 'draft',
    createdAt: '2026-07-28',
    updatedAt: '2026-07-28',
  },
]

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'john.doe@example.com',
    username: 'johndoe',
    displayName: 'John Doe',
    bio: 'Webtoon enthusiast',
    coinBalance: 150,
    status: 'active',
    createdAt: '2026-01-15',
    lastLoginAt: '2026-04-27',
  },
  {
    id: '2',
    email: 'jane.smith@example.com',
    username: 'janesmith',
    displayName: 'Jane Smith',
    bio: 'Romance lover',
    coinBalance: 320,
    status: 'active',
    createdAt: '2026-02-20',
    lastLoginAt: '2026-04-26',
  },
  {
    id: '3',
    email: 'mike.wilson@example.com',
    username: 'mikewilson',
    displayName: 'Mike Wilson',
    bio: 'Action fan',
    coinBalance: 0,
    status: 'active',
    createdAt: '2026-03-10',
    lastLoginAt: '2026-04-25',
  },
  {
    id: '4',
    email: 'sarah.jones@example.com',
    username: 'sarahjones',
    displayName: 'Sarah Jones',
    bio: 'Fantasy reader',
    coinBalance: 500,
    status: 'active',
    createdAt: '2026-04-05',
    lastLoginAt: '2026-04-27',
  },
  {
    id: '5',
    email: 'david.brown@example.com',
    username: 'davidbrown',
    displayName: 'David Brown',
    bio: 'Horror fan',
    coinBalance: 75,
    status: 'banned',
    createdAt: '2026-02-28',
    lastLoginAt: '2026-04-20',
  },
]

export const mockComments: Comment[] = [
  {
    id: '1',
    userId: '1',
    user: mockUsers[0],
    webtoonId: '1',
    episodeId: '1',
    content: {
      mm: 'အရမ်းကောင်းတယ်! ဇာတ်လမ်းကို အရမ်းနှစ်သက်တယ်။',
      en: 'Amazing! I really love this story.',
    },
    likeCount: 24,
    status: 'visible',
    createdAt: '2026-04-25T10:30:00Z',
  },
  {
    id: '2',
    userId: '2',
    user: mockUsers[1],
    webtoonId: '1',
    episodeId: '1',
    content: { mm: 'ပန်းချီပုံစံက အရမ်းလှတယ်!', en: 'The art style is beautiful!' },
    likeCount: 18,
    status: 'visible',
    createdAt: '2026-04-25T11:45:00Z',
  },
]

export const mockMediaFiles: MediaFile[] = [
  {
    id: 'm1',
    name: 'cover-1.jpg',
    type: 'image',
    url: 'https://picsum.photos/seed/webtoon1/400/600',
    size: 125000,
    uploadedAt: '2026-04-20',
    category: 'covers',
  },
  {
    id: 'm2',
    name: 'cover-2.jpg',
    type: 'image',
    url: 'https://picsum.photos/seed/webtoon2/400/600',
    size: 98000,
    uploadedAt: '2026-04-21',
    category: 'covers',
  },
]

export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'a1',
    adminId: 'admin1',
    adminName: 'Admin User',
    action: 'create',
    targetType: 'webtoon',
    targetId: '1',
    targetName: { mm: 'The Last Horizon', en: 'The Last Horizon' },
    details: { mm: 'ဝက်ဘ်တွန်းအသစ် ဖန်တီးခဲ့သည်', en: 'Created new webtoon' },
    createdAt: '2026-01-22T10:00:00Z',
  },
]

export const mockReports: Report[] = [
  {
    id: 'r1',
    type: 'comment',
    reason: 'inappropriate',
    status: 'pending',
    priority: 'high',
    reporterId: 'u1',
    reporterName: 'john_doe',
    targetId: 'c1',
    targetName: { mm: 'အပိုင်း ၅ မှ မှတ်ချက်', en: 'Comment on Episode 5' },
    description: {
      mm: 'ဤမှတ်ချက်တွင် မသင့်လျော်သော စကားလုံးများ ပါဝင်နေသည်။',
      en: 'This comment contains inappropriate language.',
    },
    createdAt: '2026-04-27T12:00:00Z',
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: 't1',
    type: 'purchase',
    userId: 'u1',
    userName: { mm: 'ကိုဂျွန်', en: 'john_doe' },
    amount: 9.99,
    coins: 100,
    status: 'completed',
    description: { mm: 'ဒင်္ဂါးဝယ်ယူမှု - ၁၀၀ ဒင်္ဂါး', en: 'Coin purchase - 100 coins' },
    createdAt: '2026-04-27 14:30',
    paymentMethod: 'Credit Card',
  },
]

export const mockScheduledEpisodes: ScheduledEpisode[] = [
  {
    id: 's1',
    webtoonId: '1',
    webtoonTitle: { mm: 'The Last Horizon', en: 'The Last Horizon' },
    episodeNumber: 86,
    title: { mm: 'နောက်ဆုံးတိုက်ပွဲ', en: 'The Final Battle' },
    scheduledAt: '2026-08-18T10:00:00',
    status: 'scheduled',
  },
]

export const mockStoryChapters: StoryChapter[] = [
  {
    id: 'origin',
    sortOrder: 1,
    published: true,
    coverImage: '/about/our-story-splash.jpg',
    title: { en: 'Why we started', mm: 'ဘာကြောင့် စတင်ခဲ့သလဲ' },
    body: {
      en: 'In 2026 we started SoftGate Comic to bring curated webtoons to Myanmar readers in a format that feels local-first.\n\nThe work began as a reading portal, not a global catalog dump — titles chosen for people who actually read here.',
      mm: '၂၀၂၆ တွင် SoftGate Comic ကို စတင်ပြီး မြန်မာဖတ်ရှုသူများအတွက် စုစည်းထားသော webtoon များကို ဒေသနှင့် ကိုက်ညီသော ပုံစံဖြင့် ပေးအပ်ရန် ရည်ရွယ်ပါသည်။\n\nကမ္ဘာလုံးဆိုင်ရာ catalog ကို ပုံတူကူးခြင်းမဟုတ် — ဒီမှာ တကယ်ဖတ်သူများအတွက် ရွေးချယ်ထားသော ဇာတ်လမ်းများဖြင့် စာဖတ် portal အဖြစ် စတင်ခဲ့သည်။',
    },
  },
  {
    id: 'readers',
    sortOrder: 2,
    published: true,
    title: { en: 'Myanmar-first reading', mm: 'မြန်မာဦးစားပေး စာဖတ်မှု' },
    body: {
      en: 'English and Myanmar sit side by side in the same portal. Type, covers, and chrome are built so everyday devices and connections here stay usable.\n\nLocal-first means the reader experience is the product — not an afterthought translation of a foreign app.',
      mm: 'အင်္ဂလိပ်နှင့် မြန်မာကို portal တစ်ခုတည်းတွင် ယှဉ်တွဲထားသည်။ စာလုံး၊ မျက်နှာဖုံးနှင့် chrome ကို ဤနေရာရှိ နေ့စဉ်သုံးစက်များနှင့် ကွန်နက်ရှင်များပေါ်တွင် သုံးနိုင်အောင် တည်ဆောက်ထားသည်။\n\nဒေသဦးစားပေး ဆိုသည်မှာ စာဖတ်အတွေ့အကြုံကို ထုတ်ကုန်အဖြစ် ထားခြင်းဖြစ်သည် — နိုင်ငံခြားအက်ပ်ကို နောက်မှ ဘာသာပြန်ခြင်းမဟုတ်ပါ။',
    },
  },
  {
    id: 'community',
    sortOrder: 3,
    published: true,
    title: { en: 'Readers and creators', mm: 'ဖတ်ရှုသူနှင့် ဖန်တီးသူ' },
    body: {
      en: 'We care about community between readers and creators — comments, library, and discovery built for people who actually read here.\n\nThe portal keeps those tools in one place so a series, a comment, and a saved title are not three different products.',
      mm: 'ဖတ်ရှုသူနှင့် ဖန်တီးသူအကြား အသိုင်းအဝိုင်းကို အလေးထားသည် — မှတ်ချက်များ၊ စာကြည့်တိုက်နှင့် ရှာဖွေမှုကို ဒီမှာ တကယ်ဖတ်သူများအတွက် တည်ဆောက်ထားသည်။\n\nဇာတ်လမ်း၊ မှတ်ချက်နှင့် သိမ်းထားသော ခေါင်းစဉ်ကို ထုတ်ကုန်သုံးခု ခွဲမထားဘဲ portal တစ်ခုတည်းတွင် ထားရှိသည်။',
    },
  },
  {
    id: 'what-ships',
    sortOrder: 4,
    published: true,
    title: { en: 'What you can do today', mm: 'ယနေ့ လုပ်နိုင်သည်များ' },
    body: {
      en: 'This portal already ships a catalog, episode reader, bookmarks, a local coin wallet for demo unlocks, and account chrome on this device.\n\nIf a feature is not in that list, it is not pretending to exist on About.',
      mm: 'ဤ portal တွင် catalog၊ အပိုင်းလိုက် ဖတ်ရှုခြင်း၊ bookmark များ၊ demo ဖွင့်ရန် စက်တွင်း coin ပိုက်ဆံအိတ်နှင့် ဤစက်ပေါ်ရှိ အကောင့် chrome တို့ ပါဝင်ပြီးသားဖြစ်သည်။\n\nထိုစာရင်းတွင် မပါသော အရာကို About တွင် ရှိပြီးသားဟု မဟန်ဆောင်ပါ။',
    },
  },
  {
    id: 'demo',
    sortOrder: 5,
    published: true,
    title: { en: 'A working demo', mm: 'လုပ်ဆောင်နေသော demo' },
    body: {
      en: 'This portal is a working demo: real UI flows on mock data while we iterate toward production APIs.\n\nWhat you tap is real in the browser. What you do not see is a live backend — and we say so.',
      mm: 'ဤ portal သည် လုပ်ဆောင်နေသော demo ဖြစ်သည် — mock data ပေါ်တွင် အမှန်တကယ် UI စီးဆင်းမှုများဖြင့် ထုတ်လုပ်ရေး API သို့ တိုးတက်နေပါသည်။\n\nနှိပ်လိုက်သောအရာသည် ဘရောက်ဇာထဲတွင် အမှန်ဖြစ်သည်။ မမြင်ရသောအရာသည် live backend ဖြစ်သည် — ထိုအချက်ကို ရိုးသားစွာ ပြောပါသည်။',
    },
  },
  {
    id: 'next',
    sortOrder: 6,
    published: true,
    title: { en: 'What we are aiming for', mm: 'ရည်မှန်းထားသည်များ' },
    body: {
      en: 'The aim is a production-ready home for Myanmar webtoons — real APIs, real creator tools, and a reading community that grows beyond this demo.\n\nThat is a direction, not a claim that those systems already ship.',
      mm: 'ရည်မှန်းချက်မှာ မြန်မာ webtoon များအတွက် production-ready နေအိမ် — အမှန်တကယ် API များ၊ ဖန်တီးသူကိရိယာများနှင့် ဤ demo ထက် ကျော်လွန်ကြီးထွားမည့် စာဖတ်အသိုင်းအဝိုင်း ဖြစ်သည်။\n\n၎င်းသည် ဦးတည်ချက်ဖြစ်သည်။ ထိုစနစ်များ ယခုတင်ပြီးသားဟု မဆိုလိုပါ။',
    },
  },
  {
    id: 'unpublished-seed',
    sortOrder: 99,
    published: false,
    title: { en: 'Staff draft', mm: 'ဝန်ထမ်း မူကြမ်း' },
    body: {
      en: 'This chapter is not published.',
      mm: 'ဤအခန်းကို ထုတ်ဝေမထားပါ။',
    },
  },
]

export const getSharedData = (): SharedData => ({
  dashboardStats: mockDashboardStats,
  revenueData: mockRevenueData,
  userGrowthData: mockUserGrowthData,
  popularWebtoons: mockPopularWebtoons,
  authors: mockAuthors,
  genres: mockGenres,
  webtoons: mockWebtoons,
  episodes: mockEpisodes,
  users: mockUsers,
  comments: mockComments,
  mediaFiles: mockMediaFiles,
  activityLogs: mockActivityLogs,
  reports: mockReports,
  transactions: mockTransactions,
  scheduledEpisodes: mockScheduledEpisodes,
})

export const exportToJSON = (data: SharedData): string => {
  return JSON.stringify(data, null, 2)
}

export const importFromJSON = (jsonString: string): SharedData => {
  try {
    return JSON.parse(jsonString) as SharedData
  } catch {
    throw new Error('Invalid JSON format')
  }
}

function fillEpisodeStripImages() {
  const coverByWebtoon = Object.fromEntries(mockWebtoons.map((w) => [w.id, w.coverImage]))
  for (const episode of mockEpisodes) {
    const cover = coverByWebtoon[episode.webtoonId]
    if (!cover) continue
    if (episode.images.length === 0) {
      episode.images = [cover, cover, cover, cover, cover]
    }
  }
}

fillEpisodeStripImages()

export const SHARED_DATA_SCHEMA_VERSION = 14

export const applyCatalogSeed = (stored: SharedData): SharedData => stored
